// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnkrxrxwavhynqushume.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRua3J4cnh3YXZoeW5xdXNodW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzA4NDgsImV4cCI6MjA2MjgwNjg0OH0.dXWwQauHMNhz2GYq8NMyyzk8N76kCR4W_FmYORdJtP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);